### ISSUE TITLE
Add image processing support for Tesseract into Apache Tika

### ISSUE THREAD

**Issue by karanjeets** [USCDataScience/counterfeit-electronics-tesseract#1]
Use programs like "imagemagik" and "convert" (only which are under Apache license) to preprocess image before passing it to Tesseract.

**Comment by karanjeets** [comment]
Done. Added ImageMagik in Tika

thanks @Zarana-Parekh

**Comment by chrismattmann** [comment]
great work @karanjeets @Zarana-Parekh
